#!/usr/bin/env bash
# edit a note and push changes
# if I edit a personal note, sync it
# correctly based on the machine I'm on

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}/../src/content" || exit $?

PERSONAL_NOTES="${XDG_DOCUMENTS_DIR}/Notes/exo"

if [[ ! -d "${PERSONAL_NOTES}" ]]; then
	echo "Personal notes directory not found: ${PERSONAL_NOTES}" >&2
	exit 1
fi

on_termux() {
	case "$(on_machine)" in
	android_*) return 0 ;;
	*) return 1 ;;
	esac
}

rg_lines() {
	PICKED_LINE="$(rg --no-heading --with-filename --line-number --color ansi "$*" | fzf --ansi)" || exit $?
	[[ -z "${PICKED_LINE}" ]] && return 1
	printf '%s\n' "${PICKED_LINE}" | cut -d':' -f'1-2'
}

declare -a RG_PARTS
# split into filename and line number
readarray -d ':' -t RG_PARTS < <(rg_lines "$@")
[[ -z "${RG_PARTS[*]}" ]] && exit 1
# arithmetic substitution removes extra newline from number
editor "+$((RG_PARTS[1]))" "${RG_PARTS[0]}"

cd "$THIS_DIR/.." || exit $?

if on_termux; then
	make copy_personal_notes
else
	make link_personal_notes
fi

./push
