#!/usr/bin/env python3
# https://en.wikipedia.org/wiki/Music-evoked_autobiographical_memory

import os
import time
from typing import NamedTuple
from pathlib import Path

import click
from autotui.shortcuts import prompt_namedtuple


class Song(NamedTuple):
    song_name: str
    url: str
    estimated_year: int
    memory: str


this_dir = Path(os.path.dirname(__file__))
content_dir = (this_dir / ".." / "src" / "content" / "meam").absolute().resolve()
assert content_dir.exists()


def edit_in_vim() -> str:
    m = click.edit(text="", editor="nvim")
    if m is None:
        raise click.Abort("No text entered")
    return m.strip()


@click.command()
def main() -> None:
    target = content_dir / f"{int(time.time())}.md"
    nt = prompt_namedtuple(Song, attr_use_values={"memory": edit_in_vim})

    assert not target.exists()
    target.write_text(
        f"""---
name: {nt.song_name}
url: {nt.url}
estimated_year: {nt.estimated_year}
---

{nt.memory}
"""
    )
    click.echo(f"Created {target}")


if __name__ == "__main__":
    main()
